EPOCHS = 50
BATCH_SIZE = 600
NUM_W = 8
n_gpu = 3
root_dir = '/data1/yogesh/dataset/imagenet/ILSVRC2012_val'
path_check = '/data1/yogesh/one-shot-det-vid/qdetr/checkpoint'
path_logs = '/data1/yogesh/one-shot-det-vid/qdetr/logs'
# data_df = '/data1/saswats/baseline/os2d/baselines/CoAE/data_new_open/grozi/classes/grozi_listed.csv'
num_classes = 2
null_class_coef = 0.5
